 export const Wordlist = [
    "NBSP", "HTML", "Machine language", "1GL", "Pipe", "Programming language", "Assembly", "ASCII", "Low-level language", "Ternary operator", "Abend"
    , "Absolute address", "Absolute Coding", "Access violation", "ACM", "ActionScript", "Action statement", "ActiveX", "Ada",
    "Add",
    "Community",
    "ADO",
    "Advanced SCSI Programming Interface",
    "Aggregation",
    "Agile development methods",
    "Agile Manifesto",
    "Alert",
    "Algol",
    "Algorithm",
    "Allocate",
    "Altair BASIC",
    "Ambient Occlusion",
    "AOP",
    "API",
    "APK",
    "Applet",
    "Argument",
    "Arithmetic operator",
    "Array",
    "Array of pointers",
    "ASCII",
    "ASP",
    "ASPI",
    "Assembler",
    "Assembly",
    "Associative operation",
    "AutoHotkey",
    "Automata-based programming",
    "Automated unit testing",
    "Automation",
    "Babel",
    "Back-end",
    "Back-face culling",
    "Background thread",
    "Backpropagation neural network",
    "Base address",
    "Batch file",
    "Batch job",
    "BCPL",
    "Bean",
    "BeanShell",
    "Binary Search",
    "Bind",
    "Bit shift",
    "Bitwise operators",
    "Block",
    "Block-based programming",
    "Block-level element",
    "BOM",
    "Bool",
    "Boolean",
    "Boolean data type",
    "Bracket",
    "Branch",
    "Brooks",
    "Browse",
    "Bug",
    "Bugfairy",
    "Bug tracking",
    "Build computer",
    "Bytecode",
    "C++",
    "C#",
    "Callback",
    "Camel book",
    "CamelCase",
    "Captured variable",
    "CC",
    "Chaos model",
    "Char",
    "Character code",
    "Character encoding",
    "Character set",
    "Circuit satisfiability problem",
    "Class",
    "Class",
    "Classpath",
    "Clojure",
    "CLOS",
    "Closure",
    "CLR",
    "COBOL",
    "Cocoa",
    "Cocoa touch",
    "Code",
    "Codepage",
    "Code refactoring",
    "CoffeeScript",
    "Command language",
    "Comment",
    "Common business oriented language",
    "Common Gateway Interface",
    "Commutative operation",
    "Compilation",
    "Compile",
    "Compiler",
    "Complementarity",
    "Compute",
    "Computer science",
    "Concat",
    "Concatenation",
    "Concurrency",
    "Conditional expression",
    "Conditional statement",
    "Constant",
    "Constructor",
    "Constructor chaining",
    "Content migration",
    "Control flow",
    "CPAN",
    "CPL",
    "Crapplet",
    "CS",
    "CSAT",
    "C sharp",
    "CSS",
    "CSS compressor",
    "CSS editor",
    "Curly bracket",
    "Curry",
    "CVS",
    "Cygwin",
    "DarkBASIC",
    "Dart",
   "Data-flow analysis",
    "Data flow diagram",
    "Dataflow Programming",
   " Datalog",
    "Data source",
    "Data structure",
    "Data type",
    "DDE",
    "Dead code",
    "Debug",
    "Debugger",
    "Debugging",
   " Declaration",
   " Declarative programming",
    "Declare",
   "Decompiler",
    "Decrement",
    "Deductive database",
    "Delimiter",
    "Dense matrix",
    "Dependent variable",
    "Deprecated",
    "Dereference operator",
    "Developer",
    "DHTML",
    "Die",
    "Diff",
    "Direct address",
    "Discrete optimization",
    "Dissembler",
    "Div",
    "Django",
    "DML",
    "Do",
    "DOM",
    "Dragon book",
    "Dribbleware",
    "Dump",
    "Dword",
    "Dylan programming language",
    "Dynamic dump",
    "Docker",
   " Eclipse",
"ECMAScript",
"Eight queens problem",
"Element",
"Elixir",
"Ellipsis",
"Else",
"Else if",
"Elsif",
"Embedded Java",
"Encapsulation",
"Encode",
"Endian",
"Endless loop",
"EOF",
"Epoch",
"Eq",
"Equal",
"Error",
"Errorlevel",
"Esac",
"Escape",
"Escape character",
"Escape sequence",
"Eval",
"Event",
"Event-driven programming",
"Event handler",
"Event listener",
"Exception",
"Exception handling",
"Exec",
"Exists",
"Exponent",
"Exponential backoff",
"Expression",

]
